### ISSUE TITLE
Eye Phone Consistent Crash

### ISSUE THREAD

**Issue by murasaki96** [Gamerbolts/bca-2.0#2]
Mura did this:
1. Get eyephone.
2. Go to eyephone settings app.
3. Press clear data.
4. Immediately crash to desktop.
Happened twice. 
https://pastebin.com/CcuxuB0s

**Comment by Gamerbolts** [comment]
The clear data was pressed when it was not hooked up to the EyeNet. Messaged mod author, will be fixed soon.
